/**
 * Demo Data Layer — Static constants for the inu demo mode
 * Persona: 지은 (27세, 직장인)
 * Structure: 4 Areas, 10 Goals, 20 Tasks
 */

import type { Direction, Area, Goal, Group, Task } from '@/types/entities'

// ============================================
// Demo User
// ============================================
export const DEMO_USER_ID = 'demo-user-000'

// ============================================
// Base dates (relative to "2 months ago")
// ============================================
const NOW = new Date()
const TWO_MONTHS_AGO = new Date(NOW.getFullYear(), NOW.getMonth() - 2, 1)
const ONE_MONTH_AGO = new Date(NOW.getFullYear(), NOW.getMonth() - 1, 1)
const THREE_WEEKS_AGO = new Date(NOW.getTime() - 21 * 24 * 60 * 60 * 1000)
const TWO_WEEKS_AGO = new Date(NOW.getTime() - 14 * 24 * 60 * 60 * 1000)
const ONE_WEEK_AGO = new Date(NOW.getTime() - 7 * 24 * 60 * 60 * 1000)

function iso(d: Date): string {
  return d.toISOString()
}

// ============================================
// Direction
// ============================================
export const DEMO_DIRECTION: Direction = {
  id: 'demo-direction-1',
  user_id: 'demo-user-1',
  statement: '건강하고 당당한 삶을 통해 가족과 오래 행복하게 살고 싶다',
  why: '이렇게 살아야 후회가 없을 것 같아서',
  status: 'active',
  version: 1,
  name: null,
  archived_at: null,
  created_at: iso(TWO_MONTHS_AGO),
  updated_at: iso(TWO_MONTHS_AGO),
}

// ============================================
// Areas (4 areas matching DEFAULT_AREAS)
// ============================================
export const DEMO_AREAS: Area[] = [
  {
    id: 'demo-area-1',
    user_id: 'demo-user-1',
    direction_id: 'demo-direction-1',
    name: '건강',
    type: 'health',
    emoji: '💪',
    color: '#6b9e7d',
    why: '건강해야 모든 걸 할 수 있으니까',
    sort_order: 'a0',
    is_active: true,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  {
    id: 'demo-area-2',
    user_id: 'demo-user-1',
    direction_id: 'demo-direction-1',
    name: '커리어',
    type: 'career',
    emoji: '📈',
    color: '#6978a8',
    why: '하고 싶은 일을 하며 살고 싶어서',
    sort_order: 'a1',
    is_active: true,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  {
    id: 'demo-area-3',
    user_id: 'demo-user-1',
    direction_id: 'demo-direction-1',
    name: '관계',
    type: 'relationships',
    emoji: '❤️',
    color: '#c07878',
    why: '소중한 사람들과 깊이 연결되고 싶어서',
    sort_order: 'a2',
    is_active: true,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  {
    id: 'demo-area-4',
    user_id: 'demo-user-1',
    direction_id: 'demo-direction-1',
    name: '취미',
    type: 'hobbies',
    emoji: '🎨',
    color: '#5e9e9e',
    why: '일만 하는 삶은 지속 가능하지 않으니까',
    sort_order: 'a3',
    is_active: true,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
]

// ============================================
// Goals (10 goals, varied statuses)
// ============================================
export const DEMO_GOALS: Goal[] = [
  // 건강 — 2 goals
  {
    id: 'demo-goal-1',
    user_id: 'demo-user-1',
    area_id: 'demo-area-1',
    name: '10km 달리기 완주',
    why: '기초체력이 모든 활동의 기반이다',
    vision: '10km를 쉬지 않고 달릴 수 있는 나',
    status: 'active',
    target_date: null,
    completed_at: null,
    sort_order: 'a0',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(ONE_MONTH_AGO),
  },
  {
    id: 'demo-goal-2',
    user_id: 'demo-user-1',
    area_id: 'demo-area-1',
    name: '수면 루틴 만들기',
    why: '수면이 회복의 핵심이니까',
    vision: null,
    status: 'maintenance',
    target_date: null,
    completed_at: iso(ONE_MONTH_AGO),
    sort_order: 'a1',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(ONE_MONTH_AGO),
  },
  // 커리어 — 3 goals
  {
    id: 'demo-goal-3',
    user_id: 'demo-user-1',
    area_id: 'demo-area-2',
    name: '영어 면접 가능 수준 달성',
    why: '더 나은 환경에서 일하고 싶어서',
    vision: '영어로 자신 있게 면접을 볼 수 있는 나',
    status: 'active',
    target_date: new Date(NOW.getFullYear(), NOW.getMonth() + 3, 1).toISOString().split('T')[0],
    completed_at: null,
    sort_order: 'a0',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  {
    id: 'demo-goal-4',
    user_id: 'demo-user-1',
    area_id: 'demo-area-2',
    name: '사이드 프로젝트 출시',
    why: '나만의 포트폴리오를 만들고 싶어서',
    vision: null,
    status: 'active',
    target_date: null,
    completed_at: null,
    sort_order: 'a1',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(ONE_MONTH_AGO),
    updated_at: iso(ONE_MONTH_AGO),
  },
  {
    id: 'demo-goal-5',
    user_id: 'demo-user-1',
    area_id: 'demo-area-2',
    name: '알고리즘 기초 완성',
    why: '기술 면접 대비가 필요해서',
    vision: null,
    status: 'backlog',
    target_date: null,
    completed_at: null,
    sort_order: 'a2',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  // 관계 — 2 goals
  {
    id: 'demo-goal-6',
    user_id: 'demo-user-1',
    area_id: 'demo-area-3',
    name: '가족과 깊은 연결 유지',
    why: '가족이 내 삶의 이유니까',
    vision: null,
    status: 'active',
    target_date: null,
    completed_at: null,
    sort_order: 'a0',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  {
    id: 'demo-goal-7',
    user_id: 'demo-user-1',
    area_id: 'demo-area-3',
    name: '친구 네트워크 넓히기',
    why: '인간관계가 기회를 만드니까',
    vision: null,
    status: 'paused',
    target_date: null,
    completed_at: null,
    sort_order: 'a1',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(THREE_WEEKS_AGO),
  },
  // 취미 — 3 goals
  {
    id: 'demo-goal-8',
    user_id: 'demo-user-1',
    area_id: 'demo-area-4',
    name: '독서 습관 만들기',
    why: '책에서 인생의 답을 찾고 싶어서',
    vision: '한 달에 2권 이상 읽는 독서가',
    status: 'active',
    target_date: null,
    completed_at: null,
    sort_order: 'a0',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  {
    id: 'demo-goal-9',
    user_id: 'demo-user-1',
    area_id: 'demo-area-4',
    name: '감사 일기 100일',
    why: '긍정적인 관점이 삶을 바꾼다고 믿어서',
    vision: null,
    status: 'active',
    target_date: null,
    completed_at: null,
    sort_order: 'a1',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  {
    id: 'demo-goal-10',
    user_id: 'demo-user-1',
    area_id: 'demo-area-4',
    name: '드로잉 배우기',
    why: '창의적인 취미가 하나 있으면 좋겠어서',
    vision: null,
    status: 'backlog',
    target_date: null,
    completed_at: null,
    sort_order: 'a2',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(ONE_MONTH_AGO),
    updated_at: iso(ONE_MONTH_AGO),
  },
]

// ============================================
// Groups (within active goals)
// ============================================
export const DEMO_GROUPS: Group[] = [
  {
    id: 'demo-group-1',
    goal_id: 'demo-goal-1',
    name: '기초 체력 만들기',
    why: '기초가 없으면 다음 단계가 어려워서',
    description: '5km를 편안하게 달릴 수 있을 때까지',
    is_completed: false,
    sort_order: 'a0',
    completed_at: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  {
    id: 'demo-group-2',
    goal_id: 'demo-goal-1',
    name: '5km 안정화',
    why: '5km를 여유롭게 달린 후 10km에 도전',
    description: null,
    is_completed: false,
    sort_order: 'a1',
    completed_at: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  {
    id: 'demo-group-3',
    goal_id: 'demo-goal-3',
    name: '리스닝 & 쉐도잉',
    why: '듣고 따라하는 게 말하기의 기초라서',
    description: null,
    is_completed: false,
    sort_order: 'a0',
    completed_at: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
]

// ============================================
// Tasks (~20 tasks, various time slots and streaks)
// ============================================
export const DEMO_TASKS: Task[] = [
  // ── 건강 / 10km 달리기 완주 (goal-1, group-1)
  {
    id: 'demo-task-1',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-1',
    group_id: 'demo-group-1',
    area_id: null,
    name: '매일 30분 러닝',
    why: '유산소가 기초 체력의 핵심이다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 30,
    time_slot: 'morning',
    specific_time: '07:00',
    streak_count: 12,
    best_streak: 15,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  {
    id: 'demo-task-2',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-1',
    group_id: 'demo-group-1',
    area_id: null,
    name: '스트레칭 10분',
    why: '부상 예방과 회복에 필수다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 10,
    time_slot: 'dawn',
    specific_time: '06:30',
    streak_count: 5,
    best_streak: 9,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a1',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  {
    id: 'demo-task-3',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-1',
    group_id: 'demo-group-1',
    area_id: null,
    name: '점심 후 산책',
    why: '오후 에너지 회복과 걷기 체력 향상',
    repeat_type: 'weekdays',
    repeat_days: null,
    duration_minutes: 15,
    time_slot: 'afternoon',
    specific_time: '13:00',
    streak_count: 4,
    best_streak: 6,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: ONE_MONTH_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a2',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(ONE_MONTH_AGO),
    updated_at: iso(NOW),
  },
  // ── 건강 / 수면 루틴 (goal-2, maintenance)
  {
    id: 'demo-task-4',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-2',
    group_id: null,
    area_id: null,
    name: '물 2L 마시기',
    why: '수분 섭취가 건강과 집중력의 기초다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 0,
    time_slot: 'anytime',
    specific_time: null,
    streak_count: 20,
    best_streak: 25,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  {
    id: 'demo-task-5',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-2',
    group_id: null,
    area_id: null,
    name: '자정 전 취침',
    why: '규칙적인 수면이 하루의 질을 결정한다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 0,
    time_slot: 'evening',
    specific_time: '23:30',
    streak_count: 8,
    best_streak: 12,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a1',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  // ── 커리어 / 영어 면접 (goal-3, group-3)
  {
    id: 'demo-task-6',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-3',
    group_id: 'demo-group-3',
    area_id: null,
    name: '영어 쉐도잉 15분',
    why: '원어민의 리듬과 발음을 체화하는 가장 빠른 방법이다',
    repeat_type: 'weekdays',
    repeat_days: null,
    duration_minutes: 15,
    time_slot: 'morning',
    specific_time: '08:00',
    streak_count: 8,
    best_streak: 12,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  {
    id: 'demo-task-7',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-3',
    group_id: 'demo-group-3',
    area_id: null,
    name: '영어 단어 20개 복습',
    why: '어휘력이 쌓여야 말하기가 쉬워진다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 10,
    time_slot: 'morning',
    specific_time: null,
    streak_count: 15,
    best_streak: 18,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a1',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  // ── 커리어 / 사이드 프로젝트 (goal-4)
  {
    id: 'demo-task-8',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-4',
    group_id: null,
    area_id: null,
    name: '사이드 프로젝트 1시간',
    why: '조금씩이라도 꾸준히 해야 실제로 완성된다',
    repeat_type: 'weekdays',
    repeat_days: null,
    duration_minutes: 60,
    time_slot: 'evening',
    specific_time: '21:00',
    streak_count: 3,
    best_streak: 5,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: ONE_MONTH_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(ONE_MONTH_AGO),
    updated_at: iso(NOW),
  },
  {
    id: 'demo-task-9',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-4',
    group_id: null,
    area_id: null,
    name: '코딩 문제 1개',
    why: '매일 1개씩 풀면 반년이면 실력이 쌓인다',
    repeat_type: 'weekdays',
    repeat_days: null,
    duration_minutes: 30,
    time_slot: 'morning',
    specific_time: null,
    streak_count: 10,
    best_streak: 14,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: ONE_MONTH_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a1',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(ONE_MONTH_AGO),
    updated_at: iso(NOW),
  },
  // ── 관계 / 가족 (goal-6)
  {
    id: 'demo-task-10',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-6',
    group_id: null,
    area_id: null,
    name: '부모님 안부 전화',
    why: '자주 연락해야 가족 간 유대가 유지된다',
    repeat_type: 'weekly',
    repeat_days: [0], // Sunday
    duration_minutes: 10,
    time_slot: 'evening',
    specific_time: '19:00',
    streak_count: 2,
    best_streak: 4,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  {
    id: 'demo-task-11',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-6',
    group_id: null,
    area_id: null,
    name: '친구에게 연락하기',
    why: '먼저 연락해야 관계가 유지된다',
    repeat_type: 'weekly',
    repeat_days: [6], // Saturday
    duration_minutes: 5,
    time_slot: 'anytime',
    specific_time: null,
    streak_count: 1,
    best_streak: 3,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a1',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  // ── 취미 / 독서 (goal-8)
  {
    id: 'demo-task-12',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-8',
    group_id: null,
    area_id: null,
    name: '독서 30분',
    why: '매일 읽으면 한 달에 1권은 거뜬하다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 30,
    time_slot: 'evening',
    specific_time: '22:00',
    streak_count: 15,
    best_streak: 20,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  // ── 취미 / 감사 일기 (goal-9)
  {
    id: 'demo-task-13',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-9',
    group_id: null,
    area_id: null,
    name: '감사일기 쓰기',
    why: '긍정적인 것에 집중하면 삶이 달라진다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 5,
    time_slot: 'evening',
    specific_time: '22:30',
    streak_count: 7,
    best_streak: 10,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  // ── 건강 / daily task (goal_id: null, area_id set)
  {
    id: 'demo-task-14',
    user_id: 'demo-user-1',
    goal_id: null,
    group_id: null,
    area_id: 'demo-area-1',
    name: '명상 10분',
    why: '하루를 차분하게 시작하는 가장 좋은 방법이다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 10,
    time_slot: 'dawn',
    specific_time: '06:00',
    streak_count: 25,
    best_streak: 30,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  // ── 커리어 / daily task
  {
    id: 'demo-task-15',
    user_id: 'demo-user-1',
    goal_id: null,
    group_id: null,
    area_id: 'demo-area-2',
    name: '업무 관련 아티클 읽기',
    why: '업계 트렌드를 따라가야 도태되지 않는다',
    repeat_type: 'weekdays',
    repeat_days: null,
    duration_minutes: 15,
    time_slot: 'morning',
    specific_time: null,
    streak_count: 6,
    best_streak: 9,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: ONE_MONTH_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(ONE_MONTH_AGO),
    updated_at: iso(NOW),
  },
  // Extra tasks with varied slots
  {
    id: 'demo-task-16',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-3',
    group_id: null,
    area_id: null,
    name: '영어 발음 연습 (앱)',
    why: '발음이 명확해야 상대방이 이해할 수 있다',
    repeat_type: 'custom',
    repeat_days: [1, 3, 5], // Mon, Wed, Fri
    duration_minutes: 10,
    time_slot: 'afternoon',
    specific_time: null,
    streak_count: 3,
    best_streak: 5,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: THREE_WEEKS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a2',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(THREE_WEEKS_AGO),
    updated_at: iso(NOW),
  },
  {
    id: 'demo-task-17',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-1',
    group_id: 'demo-group-2',
    area_id: null,
    name: '주말 장거리 러닝',
    why: '주말에 더 긴 거리를 달려야 10km 도달이 빨라진다',
    repeat_type: 'custom',
    repeat_days: [0, 6], // Sun, Sat
    duration_minutes: 60,
    time_slot: 'morning',
    specific_time: '08:00',
    streak_count: 2,
    best_streak: 4,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: ONE_MONTH_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(ONE_MONTH_AGO),
    updated_at: iso(NOW),
  },
  {
    id: 'demo-task-18',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-8',
    group_id: null,
    area_id: null,
    name: '읽은 책 한 줄 요약',
    why: '요약해야 내 것이 된다',
    repeat_type: 'weekly',
    repeat_days: [0], // Sunday
    duration_minutes: 10,
    time_slot: 'evening',
    specific_time: null,
    streak_count: 4,
    best_streak: 6,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a1',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  {
    id: 'demo-task-19',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-4',
    group_id: null,
    area_id: null,
    name: '기술 블로그 포스팅',
    why: '글로 정리하면 학습이 깊어지고 포트폴리오도 된다',
    repeat_type: 'weekly',
    repeat_days: [6], // Saturday
    duration_minutes: 60,
    time_slot: 'afternoon',
    specific_time: null,
    streak_count: 0,
    best_streak: 2,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_WEEKS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a2',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_WEEKS_AGO),
    updated_at: iso(NOW),
  },
  {
    id: 'demo-task-20',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-6',
    group_id: null,
    area_id: null,
    name: '저녁 가족 메시지',
    why: '작은 연락이 관계를 쌓는다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 5,
    time_slot: 'evening',
    specific_time: '20:00',
    streak_count: 9,
    best_streak: 12,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: ONE_WEEK_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a2',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(ONE_WEEK_AGO),
    updated_at: iso(NOW),
  },
]

// ============================================
// Lookup helpers (used by week-data.ts and review-data.ts)
// ============================================
export const DEMO_AREA_MAP = Object.fromEntries(DEMO_AREAS.map((a) => [a.id, a])) as Record<
  string,
  Area
>
export const DEMO_GOAL_MAP = Object.fromEntries(DEMO_GOALS.map((g) => [g.id, g])) as Record<
  string,
  Goal
>
export const DEMO_GROUP_MAP = Object.fromEntries(DEMO_GROUPS.map((g) => [g.id, g])) as Record<
  string,
  Group
>

// ============================================
// LITE variants — 3 Areas, 5 Goals, 8 Tasks
// ============================================

export const DEMO_AREAS_LITE: Area[] = [
  {
    id: 'demo-area-1',
    user_id: 'demo-user-1',
    direction_id: 'demo-direction-1',
    name: '건강',
    type: 'health',
    emoji: '💪',
    color: '#6b9e7d',
    why: '건강해야 모든 걸 할 수 있으니까',
    sort_order: 'a0',
    is_active: true,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  {
    id: 'demo-area-2',
    user_id: 'demo-user-1',
    direction_id: 'demo-direction-1',
    name: '커리어',
    type: 'career',
    emoji: '📈',
    color: '#6978a8',
    why: '하고 싶은 일을 하며 살고 싶어서',
    sort_order: 'a1',
    is_active: true,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  {
    id: 'demo-area-4',
    user_id: 'demo-user-1',
    direction_id: 'demo-direction-1',
    name: '취미',
    type: 'hobbies',
    emoji: '🎨',
    color: '#5e9e9e',
    why: '일만 하는 삶은 지속 가능하지 않으니까',
    sort_order: 'a2',
    is_active: true,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
]

export const DEMO_GOALS_LITE: Goal[] = [
  {
    id: 'demo-goal-1',
    user_id: 'demo-user-1',
    area_id: 'demo-area-1',
    name: '10km 달리기 완주',
    why: '기초체력이 모든 활동의 기반이다',
    vision: '10km를 쉬지 않고 달릴 수 있는 나',
    status: 'active',
    target_date: null,
    completed_at: null,
    sort_order: 'a0',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(ONE_MONTH_AGO),
  },
  {
    id: 'demo-goal-3',
    user_id: 'demo-user-1',
    area_id: 'demo-area-2',
    name: '영어 면접 가능 수준 달성',
    why: '더 나은 환경에서 일하고 싶어서',
    vision: '영어로 자신 있게 면접을 볼 수 있는 나',
    status: 'active',
    target_date: new Date(NOW.getFullYear(), NOW.getMonth() + 3, 1).toISOString().split('T')[0],
    completed_at: null,
    sort_order: 'a0',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  {
    id: 'demo-goal-4',
    user_id: 'demo-user-1',
    area_id: 'demo-area-2',
    name: '사이드 프로젝트 출시',
    why: '나만의 포트폴리오를 만들고 싶어서',
    vision: null,
    status: 'active',
    target_date: null,
    completed_at: null,
    sort_order: 'a1',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(ONE_MONTH_AGO),
    updated_at: iso(ONE_MONTH_AGO),
  },
  {
    id: 'demo-goal-8',
    user_id: 'demo-user-1',
    area_id: 'demo-area-4',
    name: '독서 습관 만들기',
    why: '책에서 인생의 답을 찾고 싶어서',
    vision: '한 달에 2권 이상 읽는 독서가',
    status: 'active',
    target_date: null,
    completed_at: null,
    sort_order: 'a0',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  {
    id: 'demo-goal-9',
    user_id: 'demo-user-1',
    area_id: 'demo-area-4',
    name: '감사 일기 100일',
    why: '긍정적인 관점이 삶을 바꾼다고 믿어서',
    vision: null,
    status: 'active',
    target_date: null,
    completed_at: null,
    sort_order: 'a1',
    status_change_reason: null,
    status_change_note: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
]

export const DEMO_GROUPS_LITE: Group[] = [
  {
    id: 'demo-group-1',
    goal_id: 'demo-goal-1',
    name: '기초 체력 만들기',
    why: '기초가 없으면 다음 단계가 어려워서',
    description: '5km를 편안하게 달릴 수 있을 때까지',
    is_completed: false,
    sort_order: 'a0',
    completed_at: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
  {
    id: 'demo-group-3',
    goal_id: 'demo-goal-3',
    name: '리스닝 & 쉐도잉',
    why: '듣고 따라하는 게 말하기의 기초라서',
    description: null,
    is_completed: false,
    sort_order: 'a0',
    completed_at: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(TWO_MONTHS_AGO),
  },
]

export const DEMO_TASKS_LITE: Task[] = [
  // 1. 명상 10분 — dawn, daily, 취미 area (daily task, no goal)
  {
    id: 'demo-task-14',
    user_id: 'demo-user-1',
    goal_id: null,
    group_id: null,
    area_id: 'demo-area-4',
    name: '명상 10분',
    why: '하루를 차분하게 시작하는 가장 좋은 방법이다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 10,
    time_slot: 'dawn',
    specific_time: '06:00',
    streak_count: 25,
    best_streak: 30,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  // 2. 스트레칭 10분 — dawn, daily, goal-1/group-1
  {
    id: 'demo-task-2',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-1',
    group_id: 'demo-group-1',
    area_id: null,
    name: '스트레칭 10분',
    why: '부상 예방과 회복에 필수다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 10,
    time_slot: 'dawn',
    specific_time: '06:30',
    streak_count: 5,
    best_streak: 9,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a1',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  // 3. 매일 30분 러닝 — morning, daily, goal-1/group-1
  {
    id: 'demo-task-1',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-1',
    group_id: 'demo-group-1',
    area_id: null,
    name: '매일 30분 러닝',
    why: '유산소가 기초 체력의 핵심이다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 30,
    time_slot: 'morning',
    specific_time: '07:00',
    streak_count: 12,
    best_streak: 15,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  // 4. 영어 쉐도잉 15분 — morning, weekdays, goal-3/group-3
  {
    id: 'demo-task-6',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-3',
    group_id: 'demo-group-3',
    area_id: null,
    name: '영어 쉐도잉 15분',
    why: '원어민의 리듬과 발음을 체화하는 가장 빠른 방법이다',
    repeat_type: 'weekdays',
    repeat_days: null,
    duration_minutes: 15,
    time_slot: 'morning',
    specific_time: '08:00',
    streak_count: 8,
    best_streak: 12,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  // 5. 물 2L 마시기 — anytime, daily, 건강 area (daily task, no goal)
  {
    id: 'demo-task-4',
    user_id: 'demo-user-1',
    goal_id: null,
    group_id: null,
    area_id: 'demo-area-1',
    name: '물 2L 마시기',
    why: '수분 섭취가 건강과 집중력의 기초다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 0,
    time_slot: 'anytime',
    specific_time: null,
    streak_count: 20,
    best_streak: 25,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  // 6. 사이드 프로젝트 1시간 — evening, weekdays, goal-4
  {
    id: 'demo-task-8',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-4',
    group_id: null,
    area_id: null,
    name: '사이드 프로젝트 1시간',
    why: '조금씩이라도 꾸준히 해야 실제로 완성된다',
    repeat_type: 'weekdays',
    repeat_days: null,
    duration_minutes: 60,
    time_slot: 'evening',
    specific_time: '21:00',
    streak_count: 3,
    best_streak: 5,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: ONE_MONTH_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(ONE_MONTH_AGO),
    updated_at: iso(NOW),
  },
  // 7. 독서 30분 — evening, daily, goal-8
  {
    id: 'demo-task-12',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-8',
    group_id: null,
    area_id: null,
    name: '독서 30분',
    why: '매일 읽으면 한 달에 1권은 거뜬하다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 30,
    time_slot: 'evening',
    specific_time: '22:00',
    streak_count: 15,
    best_streak: 20,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
  // 8. 감사일기 쓰기 — evening, daily, goal-9
  {
    id: 'demo-task-13',
    user_id: 'demo-user-1',
    goal_id: 'demo-goal-9',
    group_id: null,
    area_id: null,
    name: '감사일기 쓰기',
    why: '긍정적인 것에 집중하면 삶이 달라진다',
    repeat_type: 'daily',
    repeat_days: null,
    duration_minutes: 5,
    time_slot: 'evening',
    specific_time: '22:30',
    streak_count: 7,
    best_streak: 10,
    last_check_in_date: null,
    is_active: true,
    status: 'active',
    scheduled_date: null,
    start_date: TWO_MONTHS_AGO.toISOString().split('T')[0],
    end_date: null,
    completed_at: null,
    paused_at: null,
    status_change_reason: null,
    status_change_note: null,
    sort_order: 'a0',
    related_area_ids: [],
    related_goal_ids: [],
    cross_link_group_map: {},
    google_event_id: null,
    created_at: iso(TWO_MONTHS_AGO),
    updated_at: iso(NOW),
  },
]

export const DEMO_AREA_MAP_LITE = Object.fromEntries(
  DEMO_AREAS_LITE.map((a) => [a.id, a])
) as Record<string, Area>
export const DEMO_GOAL_MAP_LITE = Object.fromEntries(
  DEMO_GOALS_LITE.map((g) => [g.id, g])
) as Record<string, Goal>
export const DEMO_GROUP_MAP_LITE = Object.fromEntries(
  DEMO_GROUPS_LITE.map((g) => [g.id, g])
) as Record<string, Group>
